apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: tp-kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers:
  #- my-cluster-kafka-bootstrap.kafka:9092 # note the kafka namespace
  - 125.88.39.147:9092 # note the kafka namespace
  topics:
  - knative-demo-topic
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: helloworld-python
