apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: harbor.ctyun.dev:1443/hl-test/tplink-demo
        env:
        - name: INTERNAL_SCHEME
          value: "http"
        - name: REDIS_HOST
          value: "192.168.0.212"
        - name: REDIS_AUTH
          value: "D4^mF6@fM9!m"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_TIMEOUT
          value: "10"
        - name: HOST
          value: "192.168.0.216:8080"
        - name: URL_PATH
          value: "/test"

