apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: harbor.ctyun.dev:1443/hl-test/tplink-demo
        env:
        - name: TARGET
          value: "Python Sample v1"

