apiVersion: v1
kind: Secret
metadata:
  name: harbor-auth
  annotations:
    tekton.dev/docker-0: https://harbor.ctyun.dev:1443/
type: kubernetes.io/basic-auth
stringData:
    username: honglei
    password: Abcd1234
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-sa
secrets:
- name: harbor-auth
